
version: 1.0.{build}
shallow_clone: true

image:
  - Visual Studio 2017
  - Visual Studio 2019

environment:
  matrix:
    - ARCH: 32-bit
      VS17GEN: "Visual Studio 15 2017"
      VS19GEN: "Visual Studio 16 2019"
      VS19ARCH: "-A Win32"
      CMOPTS: "-DBUILD_TEST=ON -DBUILD_SHARED_LIBS=OFF"
    - ARCH: 64-bit
      VS17GEN: "Visual Studio 15 2017 Win64"
      VS19GEN: "Visual Studio 16 2019"
      VS19ARCH: "-A x64"
      CMOPTS: "-DBUILD_TEST=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_LUA_TEST=ON"

build:
  parallel: true

build_script:
  - cmd: |
      echo "image:%APPVEYOR_BUILD_WORKER_IMAGE%. arch:%ARCH%."
      cmake --version
      mkdir build
      cd build
      if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" cmake -G "%VS17GEN%" %CMOPTS% ..
      if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" cmake -G "%VS19GEN%" %VS19ARCH% %CMOPTS% ..
      cmake --build . --config Debug
      cmake --build . --config Release

test_script:
  - cmd: |
      cd test
      ctest -C Debug -V
      ctest -C Release -V
