
version: 1.0.{build}
shallow_clone: true

image:
  - Visual Studio 2017
  - Visual Studio 2019

environment:
  matrix:
    - DESC: VS 32-bit
      ARCH: ""
    - DESC: VS 64-bit
      ARCH: " Win64"

build:
  parallel: true

build_script:
  - cmd: |
      echo "image:%APPVEYOR_BUILD_WORKER_IMAGE%. arch:%ARCH%. desc:%DESC%."
      cmake --version
      mkdir build
      cd build
      set OPTS=-DBUILD_TEST=ON -DBUILD_SHARED_LIBS=OFF
      if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" cmake %OPTS% -G "Visual Studio 15 2017%ARCH%" ..
      if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" cmake %OPTS% -G "Visual Studio 16 2019%ARCH%" ..
      cmake --build . --config Debug
      cmake --build . --config Release

test_script:
  - cmd: |
      cd test
      ctest -C Debug -V
      ctest -C Release -V
