language: cpp
os: 
  - osx
  - linux
compiler:
  - clang
  - gcc
env:
  - BUILD_CONFIG=Debug
  - BUILD_CONFIG=Release
osx_image: xcode7.3

sudo: required
dist: trusty
      
install:
  - echo Lang:$LANG. OS:$TRAVIS_OS_NAME. CC:$CC.
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      if [ -z `brew list | grep doxygen` ]; then brew install doxygen; fi
      if [ -z `brew list | grep cmake` ]; then brew install cmake; fi
      if [ -z `brew list | grep lua` ]; then brew install lua; fi
      brew outdated cmake || brew upgrade cmake
      export PROJGEN=Xcode
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get -qq update
      sudo apt-get install -y cmake doxygen lua5.2
      lua -v
      which lua
      export PROJGEN="Unix Makefiles"
    fi
  
before_script:
  - cmake --version
  - mkdir build && cd build
  - echo "Generating project for $PROJGEN, config $BUILD_CONFIG."
  - cmake .. -G "$PROJGEN" -DBUILD_TEST=ON -DBUILD_TEST_LUA=ON
script:
  - cmake --build . --target ALL_BUILD --config $BUILD_CONFIG && ctest -C $BUILD_CONFIG -V

notifications:
  email:
    on_failure: change
    on_success: change


